before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libxml2-dev libxslt-dev cmake
    - gem update --system
    - bundle update

cache:
    - directories: 
        - $HOME/.m2

jdk:
    - oraclejdk8

language: ruby
rvm:
       - 2.3
       - 2.4.0
       - jruby-9.1.5.0



